In [4]:
import tensorflow as tf
import pandas as pd
import numpy as np

# mlp for multiclass classification
from numpy import argmax
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [2]:
# load the dataset
path = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
df = read_csv(path, header=None)
# split into input and output columns
X, y = df.values[:, :-1], df.values[:, -1]
# ensure all data are floating point values
X = X.astype('float32')
# encode strings to integer
y = LabelEncoder().fit_transform(y)
# split into train and test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
# determine the number of input features
n_features = X_train.shape[1]
# define model
model = Sequential()
model.add(Dense(10, activation='relu', kernel_initializer='he_normal', input_shape=(n_features,)))
model.add(Dense(8, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(3, activation='softmax'))
# compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# fit the model

(100, 4) (50, 4) (100,) (50,)


2022-06-15 09:43:39.531387: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-06-15 09:43:39.531461: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-15 09:43:39.531638: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (zam-X550IU): /proc/driver/nvidia/version does not exist
2022-06-15 09:43:39.532157: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
X_train, y_train

(array([[7.7, 2.8, 6.7, 2. ],
        [5.4, 3.4, 1.5, 0.4],
        [5.8, 2.7, 5.1, 1.9],
        [6.7, 3.1, 5.6, 2.4],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 3.1, 5.5, 1.8],
        [6.4, 2.7, 5.3, 1.9],
        [6.9, 3.1, 4.9, 1.5],
        [4.8, 3.4, 1.6, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [6.7, 3. , 5.2, 2.3],
        [5.7, 2.8, 4.5, 1.3],
        [5.1, 3.5, 1.4, 0.2],
        [5.8, 4. , 1.2, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [7.3, 2.9, 6.3, 1.8],
        [4.4, 2.9, 1.4, 0.2],
        [5.1, 3.8, 1.9, 0.4],
        [6.4, 3.2, 4.5, 1.5],
        [5.1, 3.5, 1.4, 0.3],
        [6.3, 2.3, 4.4, 1.3],
        [5.9, 3. , 4.2, 1.5],
        [6.7, 3. , 5. , 1.7],
        [7.7, 2.6, 6.9, 2.3],
        [5.7, 2.5, 5. , 2. ],
        [7.4, 2.8, 6.1, 1.9],
        [4.8, 3. , 1.4, 0.1],
        [6.1, 2.8, 4. , 1.3],
        [4.9, 3.1, 1.5, 0.1],
        [5.2, 3.5, 1.5, 0.2],
        [6. , 2.9, 4.5, 1.5],
        [5.8, 2.7, 3.9, 1.2],
        [5.5, 2.3, 4. , 1.3],
        [4

In [5]:
model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=1)
# evaluate the model
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print('Test Accuracy: %.3f' % acc)
# make a prediction
row = [5.1,3.5,1.4,0.2]
yhat = model.predict([row])
print('Predicted: %s (class=%d)' % (yhat, argmax(yhat)))

Epoch 1/150
4/4 [==============================] - 1s 5ms/step - loss: 6.5680 - accuracy: 0.3200
Epoch 2/150
4/4 [==============================] - 0s 5ms/step - loss: 6.3687 - accuracy: 0.3200
Epoch 3/150
4/4 [==============================] - 0s 4ms/step - loss: 6.1838 - accuracy: 0.3200
Epoch 4/150
4/4 [==============================] - 0s 5ms/step - loss: 6.0034 - accuracy: 0.3200
Epoch 5/150
4/4 [==============================] - 0s 6ms/step - loss: 5.8268 - accuracy: 0.3200
Epoch 6/150
4/4 [==============================] - 0s 8ms/step - loss: 5.6543 - accuracy: 0.3200
Epoch 7/150
4/4 [==============================] - 0s 6ms/step - loss: 5.4934 - accuracy: 0.3200
Epoch 8/150
4/4 [==============================] - 0s 6ms/step - loss: 5.3396 - accuracy: 0.3200
Epoch 9/150
4/4 [==============================] - 0s 6ms/step - loss: 5.1885 - accuracy: 0.3200
Epoch 10/150
4/4 [==============================] - 0s 7ms/step - loss: 5.0391 - accuracy: 0.3200
Epoch 11/150
4/4 [===========

4/4 [==============================] - 0s 6ms/step - loss: 0.9136 - accuracy: 0.3100
Epoch 85/150
4/4 [==============================] - 0s 6ms/step - loss: 0.9071 - accuracy: 0.3300
Epoch 86/150
4/4 [==============================] - 0s 6ms/step - loss: 0.9015 - accuracy: 0.3900
Epoch 87/150
4/4 [==============================] - 0s 5ms/step - loss: 0.8951 - accuracy: 0.4000
Epoch 88/150
4/4 [==============================] - 0s 6ms/step - loss: 0.8891 - accuracy: 0.4500
Epoch 89/150
4/4 [==============================] - 0s 6ms/step - loss: 0.8826 - accuracy: 0.4700
Epoch 90/150
4/4 [==============================] - 0s 6ms/step - loss: 0.8760 - accuracy: 0.5100
Epoch 91/150
4/4 [==============================] - 0s 3ms/step - loss: 0.8688 - accuracy: 0.6000
Epoch 92/150
4/4 [==============================] - 0s 6ms/step - loss: 0.8626 - accuracy: 0.6400
Epoch 93/150
4/4 [==============================] - 0s 5ms/step - loss: 0.8559 - accuracy: 0.7000
Epoch 94/150
4/4 [===============

In [7]:
# X, y
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
path = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
df = pd.read_csv(path, header=None)
df

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [22]:
mnist = tf.keras.datasets.mnist
(x_train, y_train),(x_test, y_test) = mnist.load_data()

# """
x_train, x_test = x_train / 255.0, x_test / 255.0

In [23]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
# """
model

In [8]:
model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

2022-06-10 10:57:57.095154: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2993 - accuracy: 0.9141
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1429 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1077 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0866 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0758 - accuracy: 0.9759


2022-06-10 10:58:39.712563: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 31360000 exceeds 10% of free system memory.


313/313 [==============================] - 1s 3ms/step - loss: 0.0751 - accuracy: 0.9780


[0.07513086497783661, 0.9779999852180481]

In [20]:
model.test_function

{'_self_setattr_tracking': True,
 '_is_model_for_instrumentation': True,
 '_instrumented_keras_api': True,
 '_instrumented_keras_layer_class': False,
 '_instrumented_keras_model_class': True,
 '_trainable': True,
 '_stateful': False,
 'built': True,
 '_input_spec': None,
 '_build_input_shape': TensorShape([None, 28, 28]),
 '_saved_model_inputs_spec': TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name='flatten_input'),
 '_saved_model_arg_spec': ([TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name='flatten_input')],
  {}),
 '_supports_masking': True,
 '_name': 'sequential',
 '_activity_regularizer': None,
 '_trainable_weights': [],
 '_non_trainable_weights': [],
 '_updates': [],
 '_thread_local': <_thread._local at 0x7fa26ca39040>,
 '_callable_losses': [],
 '_losses': [],
 '_metrics': [],
 '_metrics_lock': <unlocked _thread.lock object at 0x7fa26ca332d0>,
 '_dtype_policy': <Policy "float32">,
 '_compute_dtype_object': tf.float32,
 '_autocast': False,
 '_self_tracked_trackables'